---
- name: modify time zone of the machine
  timezone: name=Asia/Shanghai

- name: yum install chrony for internal time service
  yum:  name=chrony state=present

- name: start chronyd server
  systemd: name=chronyd state=started enabled=yes masked=no

- name: go to chronyd server configure
  import_tasks: setserver.yaml
  when: inventory_hostname in groups['chronyd']

- name: go to chronyd client configure
  import_tasks: setclient.yaml
  when: inventory_hostname not in groups['chronyd']

