---
- name: modify time zone of the machine
  timezone: name=Asia/Shanghai

- name: yum install chrony for internal time service
  yum:  name=chrony state=present

- name: start chronyd server
  systemd: name=chronyd state=started enabled=yes masked=no

- name: set upstream ntpserver 
  template: src=upstream.conf.j2 dest=/etc/chrony.conf mode=0644 owner=root group=root
  when: upstream is defined

- name: excute the ping 114.114.114.114 command
  shell: ping -c 2  114.114.114.114
  register: ping
  ignore_errors: true
  when: upstream is not defined

- name: set upstream server to 127.0.0.1
  template: src=local.conf.j2 dest=/etc/chrony.conf mode=0644 owner=root group=root
  when: upstream is not defined and ping.rc != 0

- name: modify the nameserver to 114.114.114.114
  copy: src=resolv.conf dest=/etc/resolv.conf mode=0644 owner=root group=root force=yes 
  when: upstream is not defined and ping.rc == 0

- name: set upstream server to default value
  template: src=chrony.conf.j2 dest=/etc/chrony.conf mode=0644 owner=root group=root
  when: upstream is not defined and ping.rc != 0

