---
- name: install glusterfs-server
  yum: name={{ item }} state=present 
  with_items: "{{ glusterfs_packages }}"
 
- name: add glusterfs to systemd 
  systemd: name=glusterd state=started enabled=yes masked=no

- name: configure  firewalld policy
  firewalld: port={{ item }} permanent=true state=enabled immediate=true
  with_items: "{{ glusterfs_firewalld_ports }}"

- name: exec the command for probe each other
  shell: gluster peer probe {{ item }}
  register: gluster_peer_probe
  with_items: "{{ groups['glusterfs'] }}"
  when: item !=  groups['glusterfs']|first  and inventory_hostname ==  groups['glusterfs']|first 

